print("hello1")
raise Exception,"hello"
print("hello2")
